### ISSUE TITLE
java.lang.ClassNotFoundException: android.support.v7.widget.Toolbar

### ISSUE THREAD

**Issue by supermamie** [CorruptedArk/open-chaos-chess#2]
I'm on a oneplus 3T running Microg for LineageOS 17.1 rom (android 10, without Google Play Services) and I just installed this app from F-Droid.
When I start a new game, it crash and I have this error log in adb :

`FATAL EXCEPTION: main
Process: dev.corruptedark.openchaoschess, PID: 11375
java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.corruptedark.openchaoschess/dev.corruptedark.openchaoschess.SinglePlayerBoard}: android.view.InflateException: Binary XML file line #34 in dev.corruptedark.openchaoschess:layout/activity_board: Binary XML file line #34 in dev.corruptedark.openchaoschess:layout/activity_board: Error inflating class android.support.v7.widget.Toolbar
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: android.view.InflateException: Binary XML file line #34 in dev.corruptedark.openchaoschess:layout/activity_board: Binary XML file line #34 in dev.corruptedark.openchaoschess:layout/activity_board: Error inflating class android.support.v7.widget.Toolbar
Caused by: android.view.InflateException: Binary XML file line #34 in dev.corruptedark.openchaoschess:layout/activity_board: Error inflating class android.support.v7.widget.Toolbar
Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.Toolbar
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at android.view.LayoutInflater.createView(LayoutInflater.java:815)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at dev.corruptedark.openchaoschess.SinglePlayerBoard.onCreate(SinglePlayerBoard.java:91)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.ClassNotFoundException: android.support.v7.widget.Toolbar
	... 28 more`

**Comment by CorruptedArk** [comment]
Thanks for letting me know about this. The 1.5.4 release currently has another issue related to gameplay that is fixed in 1.5.5. F-Droid hasn't deployed it yet, but I also have a release signed by me on this repo, if you're willing to try it out

**Comment by CorruptedArk** [comment]
@supermamie I'm closing the issue for now after my latest commit for now. If you want me to look into this issue again, please try out release [v1.5.6](https://github.com/CorruptedArk/open-chaos-chess/releases/tag/v1.5.6) and let me know if you re-encounter it.
